from pyspark.sql.types import (
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)
from pyspark.sql import Row
from datetime import datetime

# DDL script for creating an application countries table in lakehouse
# This demonstrates the basic pattern for creating Delta tables with sample data
# Based on the structure of application_countries.csv


# Define the schema for the application countries table
schema = StructType(
    [
        StructField("CountryID", IntegerType(), nullable=True),
        StructField("CountryName", StringType(), nullable=True),
        StructField("FormalName", StringType(), nullable=True),
        StructField("IsoAlpha3Code", StringType(), nullable=True),
        StructField("IsoNumericCode", StringType(), nullable=True),
        StructField("CountryType", StringType(), nullable=True),
        StructField("LatestRecordedPopulation", LongType(), nullable=True),
        StructField("Continent", StringType(), nullable=True),
        StructField("Region", StringType(), nullable=True),
        StructField("Subregion", StringType(), nullable=True),
        StructField("LastEditedBy", StringType(), nullable=True),
        StructField("ValidFrom", TimestampType(), nullable=True),
        StructField("ValidTo", TimestampType(), nullable=True),
    ]
)

# Sample data for the first 10 rows based on the CSV file
sample_data = [
    Row(
        CountryID=1,
        CountryName="Afghanistan",
        FormalName="Islamic State of Afghanistan",
        IsoAlpha3Code="AFG",
        IsoNumericCode="4",
        CountryType="UN Member State",
        LatestRecordedPopulation=28400000,
        Continent="Asia",
        Region="Asia",
        Subregion="Southern Asia",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=3,
        CountryName="Albania",
        FormalName="Republic of Albania",
        IsoAlpha3Code="ALB",
        IsoNumericCode="8",
        CountryType="UN Member State",
        LatestRecordedPopulation=3785031,
        Continent="Europe",
        Region="Europe",
        Subregion="Southern Europe",
        LastEditedBy="20",
        ValidFrom=datetime(2013, 7, 1, 16, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=4,
        CountryName="Algeria",
        FormalName="People's Democratic Republic of Algeria",
        IsoAlpha3Code="DZA",
        IsoNumericCode="12",
        CountryType="UN Member State",
        LatestRecordedPopulation=34178188,
        Continent="Africa",
        Region="Africa",
        Subregion="Northern Africa",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=6,
        CountryName="Andorra",
        FormalName="Principality of Andorra",
        IsoAlpha3Code="AND",
        IsoNumericCode="20",
        CountryType="UN Member State",
        LatestRecordedPopulation=87243,
        Continent="Europe",
        Region="Europe",
        Subregion="Southern Europe",
        LastEditedBy="15",
        ValidFrom=datetime(2015, 7, 1, 16, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=7,
        CountryName="Angola",
        FormalName="People's Republic of Angola",
        IsoAlpha3Code="AGO",
        IsoNumericCode="24",
        CountryType="UN Member State",
        LatestRecordedPopulation=12799293,
        Continent="Africa",
        Region="Africa",
        Subregion="Middle Africa",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=10,
        CountryName="Antigua and Barb.",
        FormalName="Antigua and Barbuda",
        IsoAlpha3Code="ATG",
        IsoNumericCode="28",
        CountryType="UN Member State",
        LatestRecordedPopulation=85632,
        Continent="North America",
        Region="Americas",
        Subregion="Caribbean",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=11,
        CountryName="Argentina",
        FormalName="Argentine Republic",
        IsoAlpha3Code="ARG",
        IsoNumericCode="32",
        CountryType="UN Member State",
        LatestRecordedPopulation=42550127,
        Continent="South America",
        Region="Americas",
        Subregion="South America",
        LastEditedBy="15",
        ValidFrom=datetime(2015, 7, 1, 16, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=12,
        CountryName="Armenia",
        FormalName="Republic of Armenia",
        IsoAlpha3Code="ARM",
        IsoNumericCode="51",
        CountryType="UN Member State",
        LatestRecordedPopulation=2967004,
        Continent="Asia",
        Region="Asia",
        Subregion="Western Asia",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=15,
        CountryName="Australia",
        FormalName="Commonwealth of Australia",
        IsoAlpha3Code="AUS",
        IsoNumericCode="36",
        CountryType="UN Member State",
        LatestRecordedPopulation=22997671,
        Continent="Oceania",
        Region="Oceania",
        Subregion="Australia and New Zealand",
        LastEditedBy="15",
        ValidFrom=datetime(2015, 7, 1, 16, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
    Row(
        CountryID=16,
        CountryName="Austria",
        FormalName="Republic of Austria",
        IsoAlpha3Code="AUT",
        IsoNumericCode="40",
        CountryType="UN Member State",
        LatestRecordedPopulation=8210281,
        Continent="Europe",
        Region="Europe",
        Subregion="Western Europe",
        LastEditedBy="1",
        ValidFrom=datetime(2013, 1, 1, 0, 0, 0),
        ValidTo=datetime(9999, 12, 31, 23, 59, 59),
    ),
]

# Create DataFrame with the sample data
df_with_data = target_lakehouse.spark.createDataFrame(sample_data, schema)

# Write the DataFrame to create the table with initial data
target_lakehouse.write_to_table(
    df=df_with_data, table_name="countries", schema_name=""
)